### ISSUE TITLE
Moving from Anseki's LeaderLine to your project

### ISSUE THREAD

**Issue by davidebilardello** [AhmedAyachi/LeaderLine#2]
Hi! I only discovered your repo today and immediately started changing my dependency from Anseki's library to yours! Thank you very much for the help with your "fork". However I'd like to ask you to better document the features you added, because I could use them but I don't really understand what they're for/how to use them.

The first thing I did is set the parent for the line. 
Then I saw that you gave support for page scroll, maybe you could also give support for drag event, more or less like I do with my site, you can see it here: https://escanortargaryen.dev/UltimateAdvancementGenerator/

Another thing I would like to ask you is if there is a way to make line creation faster, as you can test from my site, if you create a lot of lines, when you then recreate them all at once it takes quite a while. Could you at most create a callback of when it's finished? So at least until it finishes loading the lines I'll put a loading screen there.

Last thing, I'm also testing with show/hide of the lines, but when I call show() I get this error:
```
A disconnected element was passed.
TypeError: Cannot read properties of null (reading 'right')
    at LeaderLine.js:2:32653
    at Array.map (<anonymous>)
    at Ke (LeaderLine.js:2:32296)
    at $e (LeaderLine.js:2:44986)
    at ot.position (LeaderLine.js:2:73109)
    at LeaderLine.position (index.js:24:1)
    at LeaderLine.show (index.js:31:1)
    at advancementtab.model.ts:228:16
    at Array.forEach (<anonymous>)
    at advancementtab.model.ts:221:16
```
It would almost seem that it does not find the elements it was connected to but so far I have not been able to solve it.
Thanks again for your work and I hope you can help me out, see you soon!

**Comment by AhmedAyachi** [comment]
Hello @EscanorTargaryen , thanks for using this project.

**Docs** : you're absolutely right, I checked it and it's trash, I might've made some bad changes to the README file I was not aware of when i pushed the code. I fixed that and added an illustration to see what issues this project actually tackles.

**Give support for drag event** : can you please elaborate more.

**Error when show called** : as you can see the error occured at LeaderLine.js:2:32653, which is related to the LeaderLine actual project (v1.0.7).
Based on the error message, you're creating a line with a disconnected start/end element (not present in the DOM).
So are you referring to the error as an implementaion bug from my part or a project issue that needs to be fixed ?

**Create a callback for when it's finished** : what do you mean exactly, callback when it's finished ? meaning when the browser is done rendering the line ?
To address the performance issue, when multiple lines are created at once, try this workaround:
`
/* show loading */ 
setTimeout(()=>{
    /*render lines here
    hide loading */
},300);
`
As this code, will make line-rendering async which may remove website unresponsiveness.
Hope, i understood your point well.

Thanks for using the package again it means a lot, waiting for your response.

**Comment by davidebilardello** [comment]
Thank you very much for the advice, I think my problems probably relate to my code being quite badly written and trying to do strange things, I wouldn't really know what to ask you for yet either as the site code is private. I'll do some testing and write to you here if I need to! Can I ask you for the code for your illustration that you put in the readme?

**Comment by nkev** [comment]
@AhmedAyachi I would also like to thank you for fixing long standing requests with leader-line. 
I will move my dependency to your repo also. 

I think two things would make your changes clear to devs:
1. Create a gif-animation (like the one you have in read-me) for each of the 4 changes you made
2. Share the code for each of those demos in this repo, perhaps in a /demo folder

**Comment by AhmedAyachi** [comment]
@nkev @EscanorTargaryen , I'm sorry for replying this late, I've been busy working on a project called [Vritra](https://vritrajs.github.io/)
and as that illustration code is using it, I couldn't send you the source code any sooner.
Since the Vritra project is now live, I created a vritra app containing different examples including the one for the LeaderLine, you can then clone this [repo](https://github.com/AhmedAyachi/VritraExamples)  and start the dev server by following the steps [here](https://vritrajs.github.io/#getstarted#startanewapp).
Reminder: The project has been migrated to [LinkerLine](https://github.com/AhmedAyachi/LinkerLine), so make sure you update your dependencies.

**Comment by JuratYusup** [comment]
Hello @AhmedAyachi, In a past project of mine, I used leaderline and ran into all the problems you've since fixed in this library, which were a real pain back then. I'm truly thankful for your work in tackling those nasty issues. Even though that project is no longer active, I'll surely turn to your library for any future needs involving leaderLine.

**Comment by AhmedAyachi** [comment]
Hi @JuratYusup, I made this library because I struggled a lot with leader-line back then, it is a great library from anseki but it's lacking obviously-crutial features, and made it public to help anyone get through that hassle i've been through.
I really appreciate your feedback, but if you stared this repo, please star the [LinkerLIne](https://github.com/AhmedAyachi/LinkerLine) instead as this repo is getting no more updates nor features.
Thanks again.

**Comment by AhmedAyachi** [comment]
Hello, I encountered the issue 
```
A disconnected element was passed.
TypeError: Cannot read properties of null (reading 'right')
```
in the [VritraExamples](https://github.com/AhmedAyachi/VritraExamples) app when trying to resize the window after navigating to the linkerline route and then any other route, because the [DrawerNavigator](https://vritrajs.github.io/#vritra#drawernavigator) has memorize true by default, so the LeaderLine is trying to update start/end elements that have a removed (but cached) parent, which means they are disconnected.
This issue is going to be fixed in [LinkerLine](https://github.com/AhmedAyachi/LinkerLine) *v1.1.2*.

#### Reminder
Please update your deps to the linkerline package and restar that repo instead of this one to get new fixes and updates on your feed.
Have a nice day.
